"""
Financial Metric Registry
=========================
Central registry holding declarative MetricDefinition objects.
"""

from __future__ import annotations

import logging
from collections import defaultdict, deque

from core.services.calculation.engine import MetricDefinition

logger = logging.getLogger(__name__)


def safe_divide(num: float, den: float, error_msg: str) -> float:
    if not den:
        raise ZeroDivisionError(error_msg)
    return num / den


class MetricRegistry:
    def __init__(self) -> None:
        self._metrics: dict[str, MetricDefinition] = {}
        self._register_defaults()

    def _register_defaults(self) -> None:
        defaults = [
            MetricDefinition(
                key="gross_profit_margin",
                name="Gross Profit Margin",
                category="profitability",
                dependencies=["revenue", "cost_of_goods_sold"],
                unit="percentage",
                formula=lambda i, ctx: safe_divide(i["revenue"] - i["cost_of_goods_sold"], i["revenue"], "Revenue is zero"),
                references=[{"Type": "Accounting", "Title": "GAAP", "Section": "Income Statement"}]
            ),
            MetricDefinition(
                key="operating_margin",
                name="Operating Margin",
                category="profitability",
                dependencies=["revenue", "operating_income"],
                unit="percentage",
                formula=lambda i, ctx: safe_divide(i["operating_income"], i["revenue"], "Revenue is zero")
            ),
            MetricDefinition(
                key="net_profit_margin",
                name="Net Profit Margin",
                category="profitability",
                dependencies=["revenue", "net_income"],
                unit="percentage",
                formula=lambda i, ctx: safe_divide(i["net_income"], i["revenue"], "Revenue is zero")
            ),
            MetricDefinition(
                key="return_on_equity",
                name="Return on Equity (ROE)",
                category="profitability",
                dependencies=["net_income", "total_equity"],
                unit="percentage",
                formula=lambda i, ctx: safe_divide(i["net_income"], i["total_equity"], "Total Equity is zero")
            ),
            MetricDefinition(
                key="return_on_assets",
                name="Return on Assets (ROA)",
                category="profitability",
                dependencies=["net_income", "total_assets"],
                unit="percentage",
                formula=lambda i, ctx: safe_divide(i["net_income"], i["total_assets"], "Total Assets is zero")
            ),
            MetricDefinition(
                key="current_ratio",
                name="Current Ratio",
                category="liquidity",
                dependencies=["current_assets", "current_liabilities"],
                unit="ratio",
                formula=lambda i, ctx: safe_divide(i["current_assets"], i["current_liabilities"], "Current Liabilities is zero")
            ),
            MetricDefinition(
                key="debt_to_equity",
                name="Debt-to-Equity Ratio",
                category="leverage",
                dependencies=["total_liabilities", "total_equity"],
                unit="ratio",
                formula=lambda i, ctx: safe_divide(i["total_liabilities"], i["total_equity"], "Total Equity is zero")
            ),
            # Note: DCF metrics are generated by the Valuation Strategy directly, not here.
        ]
        for metric in defaults:
            self.register(metric)

    def register(self, metric: MetricDefinition) -> None:
        if metric.key in self._metrics:
            logger.warning("Overwriting existing metric for key '%s'.", metric.key)
        self._metrics[metric.key] = metric

    def get_metric(self, key: str) -> MetricDefinition | None:
        return self._metrics.get(key)

    def topological_order(self) -> list[str]:
        in_degree: dict[str, int] = defaultdict(int)
        graph: dict[str, list[str]] = defaultdict(list)

        for key, metric in self._metrics.items():
            in_degree.setdefault(key, 0)
            for dep in metric.dependencies:
                if dep in self._metrics:
                    graph[dep].append(key)
                    in_degree[key] += 1

        queue = deque(k for k, d in in_degree.items() if d == 0)
        order: list[str] = []

        while queue:
            node = queue.popleft()
            order.append(node)
            for neighbour in graph[node]:
                in_degree[neighbour] -= 1
                if in_degree[neighbour] == 0:
                    queue.append(neighbour)

        return order


metric_registry = MetricRegistry()
